//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace XafTasks.Module.BusinessObjects.XafTasksDB
{

    public partial class Task : XPObject
    {
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>("Title", ref fTitle, value); }
        }
        Group fGroup;
        [Association(@"TaskReferencesGroup")]
        public Group Group
        {
            get { return fGroup; }
            set { SetPropertyValue<Group>("Group", ref fGroup, value); }
        }
        bool fCompleted;
        public bool Completed
        {
            get { return fCompleted; }
            set { SetPropertyValue<bool>("Completed", ref fCompleted, value); }
        }
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>("StartDate", ref fStartDate, value); }
        }
        DateTime fDueDate;
        public DateTime DueDate
        {
            get { return fDueDate; }
            set { SetPropertyValue<DateTime>("DueDate", ref fDueDate, value); }
        }
        string fComments;
        [Size(SizeAttribute.Unlimited)]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>("Comments", ref fComments, value); }
        }
        [Association(@"TaskFileReferencesTask")]
        public XPCollection<TaskFile> TaskFiles { get { return GetCollection<TaskFile>("TaskFiles"); } }
        [Association(@"TaskImageReferencesTask")]
        public XPCollection<TaskImage> TaskImages { get { return GetCollection<TaskImage>("TaskImages"); } }
    }

}
