//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace XafTasks.Module.BusinessObjects.XafTasksDB
{

    public partial class TaskFile : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        Task fTask;
        [Association(@"TaskFileReferencesTask")]
        public Task Task
        {
            get { return fTask; }
            set { SetPropertyValue<Task>("Task", ref fTask, value); }
        }
    }

}
